/**
 * Issue #46: version 0.2 of the first Tree walked in the running app, as a reader would, with
 * every page measured and every request recorded. Issue #23's `walk.spec.ts` did this for 0.1
 * along one click path per Terminal; this suite follows every Link.
 *
 * For each language and viewport it opens a fresh browser context at the root and walks by
 * clicking: yes and no on every question Node, every Option, and after each the parent's Trail
 * Branch back. A Node already walked is still clicked into and measured from every Link that
 * leads to it, but its own Links are followed only the first time, so every Link of the Tree is
 * followed exactly once per language and viewport. The four walks run side by side, each in a
 * context of its own.
 *
 * At every page it runs the exact test of docs/specs/application.md 10.6 -- `documentElement`
 * and `body` against the window, then every element but the Carousel strip against itself --
 * and records every request against 11.5. The record is what the owner inspects (core document
 * 3.3). Like `walk.spec.ts`, writing it into the repository is opt-in, because the screenshots
 * are one machine's rendering:
 *
 *     ELSA_SHOTS=1 npm run test:first-tree -- every-link
 *
 * rewrites the generated half of `docs/screenshots/issue-46/README.md` (between its markers),
 * `requests.md` and the screenshots beside it. Name the file: a bare `ELSA_SHOTS=1` run of the
 * suite also re-takes issue #10's screenshots. A plain run writes the same record to the
 * gitignored results directory. The walk fails when a page breaks a rule, when a walk does not
 * show every Node, or when the share link does not reproduce its Trail -- after the record is
 * written, so a failure is there to read.
 *
 * The server serves `trees/ai-act-applicability-agrifood` (see playwright.first-tree.config.ts).
 */
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { expect, test, type Browser, type BrowserContext, type Page, type Request } from '@playwright/test'
import { arrived } from '../browser/arrived.ts'
import { openTree, type Tree } from '../../src/tree/loader.ts'
import type { Node } from '../../src/tree/types.ts'

const TREE = 'ai-act-applicability-agrifood'

/** Where the record goes: issue #46's tracked directory only when asked for. */
const OUT = fileURLToPath(
  process.env.ELSA_SHOTS === '1'
    ? new URL('../../docs/screenshots/issue-46/', import.meta.url)
    : new URL('.results/every-link/', import.meta.url),
)

/** The lines between which `README.md` holds what this file writes; the rest is written by hand. */
const BEGIN = '<!-- generated by tests/first-tree/every-link.spec.ts: edit the spec, not what follows -->'
const END = '<!-- end of the generated record -->'

/**
 * The guaranteed viewport of application.md 10.4, and 1280 x 800, the first of the two
 * "common laptop shapes" 10.6 measures: the other, 1024 x 768, puts a five-Option Node's
 * Options behind a Sheet (10.5, step 4), which is a degradation rather than the layout.
 */
const VIEWPORTS = [
  [1280, 640],
  [1280, 800],
] as const
const LANGUAGES = ['en', 'nl'] as const
type Lang = (typeof LANGUAGES)[number]

/** The bound of application.md 11.5: the Node a page shows and at most sixteen neighbours. */
const MAX_NODES = 17

/** Page visits per tab before the walk moves to a new one (`Walker.freshTab`). */
const FRESH_TAB_EVERY = 50

/** The centre frame: the neighbour frames are `inert` and are never clicked (11.3). */
const CENTRE = '.tree-frame:not([inert])'

/** One request, as the browser made it. */
interface Asked {
  url: string
  kind: string
  /** For a page payload: the Nodes its body carries, by `data-node`. */
  nodes?: string[]
}

/** One page visited: how it was reached, what it measured, and what it asked for. */
interface Visit {
  /** The page's number in the record, given when the record is written. */
  n: number
  lang: Lang
  viewport: string
  how: string
  url: string
  node: string
  situation: string
  inner: { w: number; h: number }
  docSH: number
  docSW: number
  bodySH: number
  bodySW: number
  bubbleSH: number
  bubbleCH: number
  overflowing: string[]
  requests: Asked[]
  error?: string
}

/** One language at one viewport: the pages it visited, in order. */
interface Run {
  lang: Lang
  viewport: string
  visits: Visit[]
}

let tree: Tree
let origin: string

/** The share button's record: what was copied, and the Trail on both sides. */
let sharing: { from: Visit; copied: string; trailFrom: string[]; opened?: Visit; trailOpened?: string[] } | null = null

/** The four situations of application.md 10.3, which is how a screenshot is chosen. */
function situation(node: Node): string {
  if (node.kind === 'question') return node.options.length > 0 ? 'question-with-options' : 'question-without-options'
  return node.kind
}

/** The page for a Trail ending at the Node shown; `lang` is omitted for the default (4.1). */
function pageUrl(ids: string[], lang: Lang): string {
  return `/${TREE}/${ids.join('/')}${lang === 'en' ? '' : `?lang=${lang}`}`
}

/** A URL of this server as a path and query; any other origin's whole. */
function local(url: string): string {
  const u = new URL(url)
  return u.origin === origin ? u.pathname + u.search : url
}

/** Every Node reachable from the root through Answers and Options, read through the loader. */
async function reachableNodes(): Promise<Map<string, Node>> {
  const nodes = new Map<string, Node>()
  const queue = [tree.manifest.root]
  while (queue.length > 0) {
    const id = queue.shift()!
    if (nodes.has(id)) continue
    const node = await tree.getNode(id)
    if (!node) throw new Error(`the loader cannot read ${id}`)
    nodes.set(id, node)
    if (node.kind === 'question') queue.push(node.answers.yes, node.answers.no)
    queue.push(...node.options.map((o) => o.target))
  }
  return nodes
}

/** One browser context walking one language at one viewport, and the requests it makes. */
class Walker {
  private visit: Visit | null = null
  private inflight = 0
  private lastActivity = Date.now()
  private readonly walked = new Set<string>()
  private readonly shot = new Set<string>()
  /** Page visits since the tab was last replaced; see `freshTab`. */
  private sinceFresh = 0
  /** Resolves once page payloads are being read on their way in; await before the first navigation. */
  readonly routed: Promise<unknown>

  page: Page

  constructor(
    page: Page,
    readonly run: Run,
    readonly nodes: Map<string, Node>,
  ) {
    this.page = page
    // Listened for on the context, so a tab `freshTab` opens is recorded the same way.
    const context = page.context()
    context.setDefaultTimeout(20_000)
    context.on('request', (request) => {
      this.inflight += 1
      this.lastActivity = Date.now()
      this.visit?.requests.push({ url: local(request.url()), kind: kindOf(request) })
    })
    const done = () => {
      this.inflight = Math.max(0, this.inflight - 1)
      this.lastActivity = Date.now()
    }
    context.on('requestfinished', done)
    context.on('requestfailed', done)
    // A page payload's body is taken on its way to the page, so the Nodes it carries can be
    // counted: Chromium does not keep a client navigation's payload for `response.body()`.
    this.routed = context.route(
      (url) => url.pathname.startsWith(`/${TREE}`),
      async (route) => {
        const response = await route.fetch()
        const body = await response.body()
        const asked = this.visit?.requests.findLast((r) => r.url === local(route.request().url()))
        if (asked) asked.nodes = [...new Set([...body.toString('utf8').matchAll(/data-node\\?"?[=:]\\?"([^"\\]+)/g)].map((m) => m[1]!))]
        await route.fulfill({ response, body })
      },
    )
  }

  /** Starts the record of the page the next action opens; its requests are counted from here. */
  private begin(how: string): Visit {
    this.visit = {
      n: 0,
      lang: this.run.lang,
      viewport: this.run.viewport,
      how,
      url: '',
      node: '',
      situation: '',
      inner: { w: 0, h: 0 },
      docSH: 0,
      docSW: 0,
      bodySH: 0,
      bodySW: 0,
      bubbleSH: 0,
      bubbleCH: 0,
      overflowing: [],
      requests: [],
    }
    this.run.visits.push(this.visit)
    this.sinceFresh += 1
    return this.visit
  }

  /** Waits for `ids` in `lang` to be the page on screen, settled, then measures it (application.md 10.6). */
  private async arrive(visit: Visit, ids: string[], lang: Lang = this.run.lang): Promise<void> {
    const id = ids[ids.length - 1]!
    const url = pageUrl(ids, lang)
    visit.url = url
    visit.node = id
    visit.situation = situation(this.nodes.get(id)!)
    await this.page.locator(`${CENTRE} .bubble[data-node="${id}"]`).waitFor()
    await arrived(this.page, new URL(url, origin).href)
    await this.settle()
    await this.page.evaluate(() => document.fonts.ready)
    Object.assign(
      visit,
      await this.page.evaluate((centre) => {
        const overflowing: string[] = []
        for (const el of document.querySelectorAll('*')) {
          // The one exemption of 10.6: the Carousel strip scrolls sideways inside its own row.
          if (el.matches('[data-carousel-strip]')) continue
          if (el.scrollHeight > el.clientHeight + 1 || el.scrollWidth > el.clientWidth + 1) {
            const name = `${el.tagName.toLowerCase()}${[...el.classList].map((c) => `.${c}`).join('')}`
            overflowing.push(`${name} holds ${el.scrollWidth}x${el.scrollHeight} in ${el.clientWidth}x${el.clientHeight}`)
          }
        }
        const bubble = document.querySelector(`${centre} .bubble`)
        return {
          inner: { w: window.innerWidth, h: window.innerHeight },
          docSH: document.documentElement.scrollHeight,
          docSW: document.documentElement.scrollWidth,
          bodySH: document.body.scrollHeight,
          bodySW: document.body.scrollWidth,
          bubbleSH: bubble?.scrollHeight ?? -1,
          bubbleCH: bubble?.clientHeight ?? -1,
          overflowing,
        }
      }, CENTRE),
    )
  }

  /** Until no request has been in flight for 400 ms, or five seconds have passed. */
  private async settle(): Promise<void> {
    const deadline = Date.now() + 5_000
    while (Date.now() < deadline && (this.inflight > 0 || Date.now() - this.lastActivity < 400)) {
      await new Promise((wake) => setTimeout(wake, 50))
    }
  }

  /** A screenshot of the viewport, named for what it shows. The document never scrolls (10.6). */
  private async screenshot(name: string): Promise<void> {
    await this.page.screenshot({ path: path.join(OUT, `${name}-${this.run.lang}-${this.run.viewport}.png`) })
  }

  /**
   * Opens the root in this context's language: English by URL, Dutch by the app's own switch,
   * clicked on the English root once that page is measured.
   */
  async open(): Promise<void> {
    const root = tree.manifest.root
    await this.routed
    let visit = this.begin('opened')
    await this.page.goto(pageUrl([root], 'en'))
    if (this.run.lang !== 'en') {
      await this.arrive(visit, [root], 'en')
      visit = this.begin('language switch')
      await this.page.locator(`.language-switch a.language[lang="${this.run.lang}"]`).click()
    }
    await this.arrive(visit, [root])
    this.walked.add(root)
    await this.shoot(visit)
    await this.explore([root])
  }

  /** Takes the screenshots this issue asks for, the first time each is due. */
  private async shoot(visit: Visit): Promise<void> {
    const node = this.nodes.get(visit.node)!
    const step = node.title.en?.match(/\((\d)\/7\)$/)
    if (this.run.lang === 'en' && step && !this.shot.has(node.id)) {
      this.shot.add(node.id)
      await this.screenshot(`jurisdiction-${step[1]}-of-7-${node.id}`)
    } else if (!this.shot.has(visit.situation)) {
      this.shot.add(visit.situation)
      await this.screenshot(`${visit.situation}-${node.id}`)
    }
  }

  /** Follows every Link of the Node at the end of `ids`, going back by the Trail after each. */
  private async explore(ids: string[]): Promise<void> {
    const node = this.nodes.get(ids[ids.length - 1]!)!
    const links: { how: string; target: string; selector: string }[] = []
    if (node.kind === 'question') {
      links.push({ how: 'yes', target: node.answers.yes, selector: `${CENTRE} .answer--yes` })
      links.push({ how: 'no', target: node.answers.no, selector: `${CENTRE} .answer--no` })
    }
    for (const option of node.options) {
      const href = pageUrl([...ids, option.target], this.run.lang)
      links.push({ how: 'option', target: option.target, selector: `${CENTRE} a.option[href="${href}"]` })
    }

    for (const link of links) {
      if (this.sinceFresh >= FRESH_TAB_EVERY) await this.freshTab(ids)
      const there = [...ids, link.target]
      const visit = this.begin(`${link.how} from ${node.id}`)
      try {
        await this.page.locator(link.selector).click()
        await this.arrive(visit, there)
        await this.shoot(visit)
        if (this.run.lang === 'en' && this.run.viewport === '1280x640' && link.target === 'end-of-walk' && !sharing) {
          await this.share(visit, there)
        }
      } catch (error) {
        visit.error = String(error).split('\n')[0]
        await this.recover(there)
      }
      if (!this.walked.has(link.target)) {
        this.walked.add(link.target)
        await this.explore(there)
      }
      const back = this.begin(`Trail back from ${link.target}`)
      try {
        await this.page.locator(`${CENTRE} .trail-step[data-parent] .trail-entry`).click()
        await this.arrive(back, ids)
      } catch (error) {
        back.error = String(error).split('\n')[0]
        await this.recover(ids)
      }
    }
  }

  /**
   * Replaces the tab with a new one at the page the walk is on. Headless Chromium's renderer
   * crashed after 119 to about 310 slides in one tab (#63), which
   * would end the walk; a tab of its own every FRESH_TAB_EVERY pages keeps it well short.
   */
  private async freshTab(ids: string[]): Promise<void> {
    const old = this.page
    this.page = await old.context().newPage()
    await old.close()
    this.sinceFresh = 0
    const visit = this.begin('the same page in a new tab (renderer crash, #63)')
    await this.page.goto(pageUrl(ids, this.run.lang))
    await this.arrive(visit, ids)
  }

  /** After a failed click: loads the page the walk expected, so the walk carries on from it. */
  private async recover(ids: string[]): Promise<void> {
    const visit = this.begin('recovery (typed URL)')
    await this.page.goto(pageUrl(ids, this.run.lang))
    await this.arrive(visit, ids)
  }

  /** The share button on a deep page, and its link opened in a fresh browser context. */
  private async share(from: Visit, ids: string[]): Promise<void> {
    await this.page.locator('.share').click()
    const copied = await this.page.evaluate(() => navigator.clipboard.readText())
    const record: NonNullable<typeof sharing> = { from, copied: local(copied), trailFrom: await trailOf(this.page) }
    sharing = record
    const fresh = await context(this.page.context().browser()!, VIEWPORTS[0])
    try {
      const walker = new Walker(await fresh.newPage(), this.run, this.nodes)
      await walker.routed
      const visit = walker.begin('share link opened in a fresh context')
      await walker.page.goto(copied)
      await walker.arrive(visit, ids)
      record.opened = visit
      record.trailOpened = await trailOf(walker.page)
      await walker.screenshot('share-link-fresh-context')
    } finally {
      await fresh.close()
    }
  }
}

/** The Trail Branches of the centre frame, by their `href`. */
async function trailOf(page: Page): Promise<string[]> {
  return page.locator(`${CENTRE} .trail-entry`).evaluateAll((links) => links.map((a) => a.getAttribute('href') ?? ''))
}

function kindOf(request: Request): string {
  if (request.resourceType() === 'document') return 'page (HTML)'
  if (request.headers()['rsc'] === '1') return 'page (payload)'
  return request.resourceType()
}

async function context(browser: Browser, [width, height]: readonly [number, number]): Promise<BrowserContext> {
  return browser.newContext({ viewport: { width, height }, permissions: ['clipboard-read', 'clipboard-write'], baseURL: origin })
}

/** What is wrong with a visit, by the rules of application.md 10.6 and 11.5; empty when nothing. */
async function problems(v: Visit): Promise<string[]> {
  const found: string[] = []
  if (v.error) found.push(`walk: ${v.error}`)
  // A page the walk left before measuring it is a gap in the record, not a clean page.
  if (v.inner.h === 0) found.push('not measured')
  for (const [name, sh, sw] of [
    ['document', v.docSH, v.docSW],
    ['body', v.bodySH, v.bodySW],
  ] as const) {
    if (sh > v.inner.h + 1) found.push(`${name} ${sh} px tall in a ${v.inner.h} px window`)
    if (sw > v.inner.w + 1) found.push(`${name} ${sw} px wide in a ${v.inner.w} px window`)
  }
  if (v.bubbleSH > v.bubbleCH + 1) found.push(`Bubble content ${v.bubbleSH} px in ${v.bubbleCH} px`)
  found.push(...v.overflowing.map((o) => `overflow: ${o}`))
  const node = await tree.getNode(v.node)
  const images = node ? [...node.images, ...node.options.flatMap((o) => o.images.slice(0, 1))].map((i) => i.file) : []
  for (const r of v.requests) {
    if (!r.url.startsWith('/')) found.push(`third-party request: ${r.url}`)
    if (/tree\.ya?ml|\/api\//.test(r.url)) found.push(`request for the Tree: ${r.url}`)
    if ((r.nodes?.length ?? 0) > MAX_NODES) found.push(`${r.url} carries ${r.nodes!.length} Nodes`)
    const image = r.url.match(/^\/images\/([^?]+)/)
    if (image && !images.includes(decodeURIComponent(image[1]!))) found.push(`image of an off-screen Node: ${r.url}`)
  }
  return found
}

/** The generated half of `README.md` and `requests.md`: every page, every number, every request. */
async function writeRecord(runs: Run[], nodes: Map<string, Node>): Promise<void> {
  const visits = runs.flatMap((run) => run.visits)
  visits.forEach((v, i) => (v.n = i + 1))

  const lines: string[] = [BEGIN, '', '## The count', '', `Nodes the loader reaches from the root: **${nodes.size}**.`, '']
  lines.push('| language | viewport | pages visited | distinct Nodes shown | Links followed | Trail backs | Terminals reached | pages with a problem |')
  lines.push('|---|---|---|---|---|---|---|---|')
  for (const run of runs) {
    const mine = run.visits.filter((v) => !v.how.startsWith('share'))
    let bad = 0
    for (const v of mine) if ((await problems(v)).length > 0) bad += 1
    lines.push(
      `| ${run.lang} | ${run.viewport} | ${mine.length} | ${shownNodes(mine).size} | ${mine.filter((v) => /^(yes|no|option) from/.test(v.how)).length} | ` +
        `${mine.filter((v) => v.how.startsWith('Trail back')).length} | ${new Set(mine.filter((v) => v.situation === 'terminal').map((v) => v.node)).size} | ${bad} |`,
    )
  }
  lines.push('', `All pages visited, the share link's included: **${visits.length}**.`, '')
  if (sharing) {
    lines.push('## The share link', '')
    lines.push(`- Copied on \`${sharing.from.url}\` (page ${sharing.from.n}): \`${sharing.copied}\``)
    lines.push(
      `- Trail Branches on the page it was copied from: ${sharing.trailFrom.length}; on the page opened in a fresh context (page ${sharing.opened?.n}): ` +
        `${sharing.trailOpened?.length}; identical: ${JSON.stringify(sharing.trailFrom) === JSON.stringify(sharing.trailOpened)}`,
      '',
    )
  }
  lines.push('## Every page', '')
  lines.push(
    '`document` and `body` are the element\'s `scrollHeight` x `scrollWidth` in the window\'s `innerHeight` x `innerWidth`; `Bubble` is the centre Bubble\'s `scrollHeight` / `clientHeight`; ' +
      '`overflowing elements` counts every other element, the Carousel strip excepted, whose content is larger than itself; `requests` counts every request from the action that opened the page ' +
      'to the one that left it (listed in `requests.md`); `payload Nodes` is the most Nodes one page response carried.',
    '',
  )
  lines.push('| # | language | viewport | reached by | URL | document | body | Bubble | overflowing elements | requests | payload Nodes | problem |')
  lines.push('|---|---|---|---|---|---|---|---|---|---|---|---|')
  for (const v of visits) {
    const found = await problems(v)
    const payload = Math.max(0, ...v.requests.map((r) => r.nodes?.length ?? 0))
    const inner = `${v.inner.h}x${v.inner.w}`
    lines.push(
      `| ${v.n} | ${v.lang} | ${v.viewport} | ${v.how} | \`${v.url}\` | ${v.docSH}x${v.docSW} in ${inner} | ${v.bodySH}x${v.bodySW} in ${inner} | ` +
        `${v.bubbleSH} / ${v.bubbleCH} | ${v.overflowing.length} | ${v.requests.length} | ${payload || ''} | ${found.join('; ').replaceAll('|', '\\|')} |`,
    )
  }
  lines.push('', END)
  await writeReadme(lines.join('\n'))

  const requests = ['# Every request, by page', '', 'The page numbers are those of `README.md`. A path is this server; anything else would be printed whole.', '']
  requests.push('| page | kind | URL | Nodes carried |', '|---|---|---|---|')
  for (const v of visits) {
    for (const r of v.requests) requests.push(`| ${v.n} | ${r.kind} | \`${r.url}\` | ${r.nodes ? r.nodes.length : ''} |`)
  }
  await writeFile(path.join(OUT, 'requests.md'), requests.join('\n') + '\n')
}

/** Puts `generated` between the README's markers, or into `record.md` of a plain run. */
async function writeReadme(generated: string): Promise<void> {
  if (process.env.ELSA_SHOTS !== '1') {
    await writeFile(path.join(OUT, 'record.md'), generated + '\n')
    return
  }
  const file = path.join(OUT, 'README.md')
  const readme = await readFile(file, 'utf8')
  const begin = readme.indexOf(BEGIN)
  const end = readme.indexOf(END)
  if (begin < 0 || end < begin) throw new Error(`${file} lacks the markers the record is written between`)
  await writeFile(file, readme.slice(0, begin) + generated + readme.slice(end + END.length))
}

/** The Nodes a run's pages showed, measured and without a walk error. */
function shownNodes(visits: Visit[]): Set<string> {
  return new Set(visits.filter((v) => v.bubbleSH >= 0 && v.inner.h > 0 && !v.error).map((v) => v.node))
}

test('every Link of the first Tree, in both languages at both viewports, measured and recorded', async ({ browser, baseURL }) => {
  // About seven minutes for the four walks side by side on one laptop; one walk alone takes about six.
  test.setTimeout(40 * 60_000)
  origin = new URL(baseURL!).origin
  tree = await openTree(fileURLToPath(new URL(`../../trees/${TREE}`, import.meta.url)))
  const nodes = await reachableNodes()
  await mkdir(OUT, { recursive: true })

  const runs: Run[] = VIEWPORTS.flatMap(([w, h]) => LANGUAGES.map((lang) => ({ lang, viewport: `${w}x${h}`, visits: [] })))
  await Promise.all(
    runs.map(async (run) => {
      const ctx = await context(browser, VIEWPORTS.find(([w, h]) => `${w}x${h}` === run.viewport)!)
      try {
        await new Walker(await ctx.newPage(), run, nodes).open()
      } finally {
        await ctx.close()
      }
    }),
  )
  await writeRecord(runs, nodes)

  for (const run of runs) {
    const mine = run.visits.filter((v) => !v.how.startsWith('share'))
    expect.soft(shownNodes(mine).size, `${run.lang} ${run.viewport}: distinct Nodes shown`).toBe(nodes.size)
  }
  const broken: string[] = []
  for (const v of runs.flatMap((run) => run.visits)) {
    const found = await problems(v)
    if (found.length > 0) broken.push(`page ${v.n} ${v.url}: ${found.join('; ')}`)
  }
  expect.soft(broken, 'pages with a problem').toEqual([])
  expect(sharing?.trailOpened, 'the share link opened on the Trail it was copied from').toEqual(sharing?.trailFrom)
})
